POST http://localhost:8084/public/job/v1
Content-Type: application/json

{
  "jobTitle": "rrdf",
  "jobGroup": "ffff",
  "salary": "2333",
  "jobDescription": "fgh",
  "skill": "hhhhhhhhhh",
  "company": {
    "id": 10
  }
}
### ثبت نام آگهی
POST http://localhost:8084/public/process_register
Content-Type: application/json

{
"email": "sara@gmail.com",
"password": "sara",
"firstName": "sara",
"lastName": "Pit",
"confirmedPassword": "sara"
}
### ثبت نام کاربر
GET http://localhost:8084/public/job/v1?jobTitle=برنامه نویس


### جستجو شغل

POST http://localhost:8084/public/company/v1
Content-Type: application/json

{
  "companyName": "اه",
  "city": "ffff",
  "aboutCompany": "یه شرکت بزرگه",
  "address": "ایران"
}

### ثبت شرکت

POST http://localhost:8084/upload
Content-Type: multipart/form-data; boundary=RequestBody

--RequestBody
Content-Disposition: form-data; name="file"; filename="ZeinabShajarkar.pdf"<"H:\resume"

--RequestBody--

### آپلود رزومه




