GET http://localhost:8084/public/provinces/v1

### گرفتن لیست شهر ها------------------------------------------------------

GET http://localhost:8084/public/job-groups/v1

### گرفتن لیست گروه های شغلی

POST http://localhost:8084/public/company/v1
Content-Type: application/json

{
  "companyName": "زینب",
  "city": 27,
  "aboutCompany": "شرکتی بزرگ و با تعداد 200 کارمند",
  "address": " خیابان انقلاب،پلاک 200",
  "email": "zshajarkar2@yahoo.com",
  "password": "sSSssd78@5*",
  "confirmPassword": "sSSssd78@5*"
}

### ثبت شرکت ------------------------------------------------------------------


POST http://localhost:8084/public/job/v1
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ6c2hhamFya2FyMkB5YWhvby5jb21AY29tcGFueSIsImlhdCI6MTY0NTI4NzIwMCwiZXhwIjoxNjQ1MzczNjAwfQ.Nid7kcKyMKNq4vfXL_FxmRF_HaOk1HNIj-PTxoyRE8KYfQdMXNJgzIBDBqBTBlIb5WBo9j6M1v2C1ljOdqh-PQ
Content-Type: application/json

{
  "jobTitle": "بنا",
  "jobGroup": "طراحی",
  "salary": 13,
  "jobDescription": "با محیطی مفرح",
  "skills": [
    {
      "id": null,
      "name": "جاوا"
    },
    {
      "id": null,
      "name": "hi"
    }
  ]
}

### ثبت نام آگهی --------------------------------------------------------------------
### پیش نیاز ثبت آگهی ثبت شرکت است ---------------------------------------------------
POST http://localhost:8084/public/user/v1/process_register
Content-Type: application/json

{
  "email": "abdolVahab@yahoo.com",
  "password": "sSSssd78@5*",
  "firstName": "عبدال وهاب",
  "lastName": "شجرکار       ",
  "confirmedPassword": "sSSssd78@5*"
}

### ثبت نام کاربر ----------------------------------------------------------------------
GET http://localhost:8084/public/job/v1?city=29

### جستجو شغل ----------------------------------------------------------------------

# curl --location --request POST 'http://localhost:8084/upload/job/1/user/1'
#--form 'file=@"/H:/why.png"'
POST http://localhost:8084/public/resume/v1/job/7
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ6c2hhamFya2FyQHlhaG9vLmNvbSIsImlhdCI6MTY0NTI4OTY0MSwiZXhwIjoxNjQ1Mzc2MDQxfQ.SQYG8wcmPrRLHQfi-viuQZZkUDW-PXcA2csrmOsW7MeaoopWRlQ8Wnh5Icmafh5eo3eSPaLmcL5ZtQbGEnvcsA
Content-Type: multipart/form-data; boundary=requestBody

--requestBody
Content-Disposition: form-data; name="file"; filename="test.jpg""< "\D:\data\test.jpg"

--requestBody--

### آپلود رزومه -نیاز به header دارد

POST http://localhost:8084/public/user/v1/sign_in
Content-Type: application/json

{
  "email": "abdolVahab@yahoo.com",
  "password": "sSSssd78@5*"
}

### ورود کارجو

POST http://localhost:8084/public/company/v1/sign-in
Content-Type: application/json

{
  "email": "zshajarkar2@yahoo.com",
  "password": "sSSssd78@5*"
}

### ورود شرکت
GET http://localhost:8084/public/skill/v1

### گرفتن لیست مهارت های ثبت شده

GET http://localhost:8084/public/job/v1/companyId
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ6c2hhamFya2FyMkB5YWhvby5jb21AY29tcGFueSIsImlhdCI6MTY0NTI4NzIwMCwiZXhwIjoxNjQ1MzczNjAwfQ.Nid7kcKyMKNq4vfXL_FxmRF_HaOk1HNIj-PTxoyRE8KYfQdMXNJgzIBDBqBTBlIb5WBo9j6M1v2C1ljOdqh-PQ

### گرفتن لیست شغل ثبت شده هر کمپانی

GET http://localhost:8084/public/user/v1/jobId/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ6c2hhamFya2FyMkB5YWhvby5jb21AY29tcGFueSIsImlhdCI6MTY0NTI4NzIwMCwiZXhwIjoxNjQ1MzczNjAwfQ.Nid7kcKyMKNq4vfXL_FxmRF_HaOk1HNIj-PTxoyRE8KYfQdMXNJgzIBDBqBTBlIb5WBo9j6M1v2C1ljOdqh-PQ

### گرفتن لیست کاربرانی که برای ایند شغل رزومه ارسال کرده اند

GET http://localhost:8084/public/resume/v1/files/job/1/user-id/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ6c2hhamFya2FyMkB5YWhvby5jb21AY29tcGFueSIsImlhdCI6MTY0NTI4NzIwMCwiZXhwIjoxNjQ1MzczNjAwfQ.Nid7kcKyMKNq4vfXL_FxmRF_HaOk1HNIj-PTxoyRE8KYfQdMXNJgzIBDBqBTBlIb5WBo9j6M1v2C1ljOdqh-PQ

### دانلود رزومه
