POST http://localhost:8084/public/job/v1
Content-Type: application/json

{
  "jobTitle": "برنامه نویس",
  "jobGroup": "ffff",
  "salary": "2333",
  "jobDescription": "fgh",
  "skill": "hhhhhhhhhh",
  "company": {
    "id": 1
  }
}

### ثبت نام آگهی
POST http://localhost:8084/public/process_register
Content-Type: application/json

{
  "email": "saudd87@gmail.com",
  "password": "sSSssd78@5*",
  "firstName": "saud",
  "lastName": "saud",
  "confirmedPassword": "sSSssd78@5*"
}

### ثبت نام کاربر
GET http://localhost:8084/public/job/v1?jobTitle=برنامه نویس


### جستجو شغل

POST http://localhost:8084/public/company/v1
Content-Type: application/json

{
  "companyName": "wow",
  "city": "tehran",
  "aboutCompany": "یه شرکت بزرگه",
  "address": "ایران"
}

### ثبت شرکت

# curl --location --request POST 'http://localhost:8084/upload/job/1/user/1'
#--form 'file=@"/H:/why.png"'
POST http://localhost:8084/upload/job/2/user/1
Content-Type: multipart/form-data; boundary=requestBody

--requestBody
Content-Disposition: form-data; name="file"; filename="why.png""< "\H:\why.png"

--requestBody--

### آپلود رزومه

GET http://localhost:8084/files




